railstutorial:  "https://www.railstutorial.org/"
newrailstutorial: http://news.railstutorial.org/
michael_hartl: "http://www.michaelhartl.com/"
railstutorial_book: "https://www.railstutorial.org/book"
screencasts: "http://screencasts.railstutorial.org/"
contactpage: "https://www.railstutorial.org/contact"
